In [17]:
import pandas as pd
import os

In [18]:
folder_data = os.listdir(r'C:\Users\User\Desktop\j\lessons\lesson_4\Res_Tree')
folder_data

['F000545', 'F000570', 'M000547']

In [19]:
path = r'C:\Users\User\Desktop\j\lessons\lesson_4\Res_Tree\F000545\res_2019.09.10_0.0_6493B6_Container-dat_2110_84-99-223_F000545\meals_list_2.txt'

In [23]:
data = open(path).readlines()
data

['-------------------------------------------------------\n',
 '-------------------------------------------------------\n',
 'Data log format: Descent DB log\n',
 '\n',
 '  Intake Params check: INTAKE PARAMS DIFFER FROM THEIR DEFAULTS!!!\n',
 '  Power cycle emulation: disabled\n',
 '\n',
 '  Build Mode:   HB_ITS_ONLY\n',
 '-------------------------------------------------------\n',
 '\n',
 '--- Non-deleted saved meals -----------------------\n',
 ' Meal#;        Date; Start;   End; Flags;    E-IN;    Cbh;    Fat;    Pro;  S. tstamp; End tstamp; Minutes;  Recs; First;  Last;    Type; Frags;\n',
 '     0;  09.09.2019; 16:22; 17:58;  0x84;  190.19;  16.27;   9.88;   9.06; 1568035377; 1568041082;      96;    95;     4;    98; F3-Meal;\n',
 '     1;  09.09.2019; 18:17; 20:10;  0x84;  256.30;  19.55;  14.06;  12.89; 1568042235; 1568049032;     114;   122;   108;   229; F3-Meal;\n',
 '     2;  09.09.2019; 20:53; 21:39;  0x84;   67.63;   7.87;   2.85;   2.62; 1568051580; 1568054372;      47;    47;   271;   317; F3-Meal;\n',
 '     3;  09.09.2019; 23:00; 00:22;  0x84;  179.50;  15.13;   9.39;   8.61; 1568059227; 1568064143;      82;    82;   397;   478; F3-Meal;\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- All saved meals -------------------------------\n',
 "     there's no per-meal data\n",
 '-----------------------------------------------------\n',
 '\n',
 '--- Total per-file (0: by summaries, 1: by meals) -\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '09.09.2019 16:19:55; 09.09.2019 23:59:07;       0;       0; 1568073547;   644.59;   54.68;   33.62;   30.82;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '09.09.2019 16:22:57; 10.09.2019 00:22:23;       1;       0; 1568074943;   644.59;   54.68;   33.62;   30.82;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- Summary change history --------------------------\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '09.09.2019 16:19:55; 09.09.2019 23:59:07;       0;       0; 1568073547;   644.59;   54.68;   33.62;   30.82;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n',
 '-------------------------------------------------------\n',
 '-------------------------------------------------------\n',
 'Data log format: Descent DB log\n',
 '\n',
 '\n',
 '  Intake Params check: INTAKE PARAMS DIFFER FROM THEIR DEFAULTS!!!\n',
 '  Power cycle emulation: disabled\n',
 '\n',
 '  Build Mode:   HB_ITS_ONLY\n',
 '-------------------------------------------------------\n',
 '\n',
 '\n',
 '\n',
 '--- Non-deleted saved meals -----------------------\n',
 ' Meal#;        Date; Start;   End; Flags;    E-IN;    Cbh;    Fat;    Pro;  S. tstamp; End tstamp; Minutes;  Recs; First;  Last;    Type; Frags;\n',
 '     0;  09.09.2019; 23:00; 00:22;  0x84;  179.50;  15.13;   9.39;   8.61; 1568059227; 1568064143;      82;    82;   397;   478; F3-Meal;\n',
 '     1;  10.09.2019; 01:32; 02:11;  0x84;   47.41;   5.77;   1.92;   1.76; 1568068330; 1568070697;      40;    43;   544;   586; F3-Meal;\n',
 '     2;  10.09.2019; 03:50; 05:31;  0x84;  175.42;  15.90;   8.83;   8.09; 1568076644; 1568082713;     102;   107;   678;   784; F3-Meal;\n',
 '     3;  10.09.2019; 09:17; 10:59;  0x84;  300.08;  21.59;  16.87;  15.47; 1568096246; 1568102375;     103;    98;  1007;  1104; F3-Meal;\n',
 '     4;  10.09.2019; 11:14; 12:07;  0x84;   76.57;   8.63;   3.32;   3.04; 1568103286; 1568106442;      53;    53;  1123;  1175; F3-Meal;\n',
 '     5;  10.09.2019; 12:07; 12:47;  0x84;   45.03;   5.87;   1.70;   1.56; 1568106442; 1568108870;      41;    41;  1175;  1215; F3-Meal;\n',
 '     6;  10.09.2019; 13:19; 16:05;  0x84;  371.60;  26.78;  20.88;  19.14; 1568110750; 1568120704;     166;   162;  1246;  1407; F3-Meal;\n',
 '     7;  10.09.2019; 16:37; 18:17;  0x84;  255.73;  18.62;  14.31;  13.12; 1568122645; 1568128654;     101;   100;  1442;  1541; F3-Meal;\n',
 '     8;  10.09.2019; 19:36; 21:34;  0x84;  303.56;  22.04;  17.01;  15.59; 1568133387; 1568140488;     119;   118;  1619;  1736; F3-Meal;\n',
 '     9;  10.09.2019; 21:34; 23:14;  0x84;  186.06;  15.87;   9.68;   8.87; 1568140488; 1568146496;     101;    74;  1736;  1809; F3-Meal;\n',
 '    10;  10.09.2019; 23:14; 02:44;  0x84;  460.76;  37.92;  24.40;  22.37; 1568146496; 1568159058;     210;   234;  1809;  2042; F3-Meal;\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- All saved meals -------------------------------\n',
 "     there's no per-meal data\n",
 '-----------------------------------------------------\n',
 '\n',
 '--- Total per-file (0: by summaries, 1: by meals) -\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '10.09.2019 00:00:07; 10.09.2019 23:59:26;       0;       0; 1568159966;  1909.69;  153.36;  102.34;   93.81;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '10.09.2019 01:32:10; 11.09.2019 02:44:18;       1;       0; 1568169858;  1909.69;  153.36;  102.34;   93.81;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- Summary change history --------------------------\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '10.09.2019 00:00:07; 10.09.2019 23:59:26;       0;       0; 1568159966;  1909.69;  153.36;  102.34;   93.81;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n',
 '-------------------------------------------------------\n',
 '-------------------------------------------------------\n',
 'Data log format: Descent DB log\n',
 '\n',
 '\n',
 '  Intake Params check: INTAKE PARAMS DIFFER FROM THEIR DEFAULTS!!!\n',
 '  Power cycle emulation: disabled\n',
 '\n',
 '  Build Mode:   HB_ITS_ONLY\n',
 '-------------------------------------------------------\n',
 '\n',
 '\n',
 '--- Non-deleted saved meals -----------------------\n',
 ' Meal#;        Date; Start;   End; Flags;    E-IN;    Cbh;    Fat;    Pro;  S. tstamp; End tstamp; Minutes;  Recs; First;  Last;    Type; Frags;\n',
 '     0;  10.09.2019; 23:14; 02:44;  0x84;  460.76;  37.92;  24.40;  22.37; 1568146496; 1568159058;     210;   234;  1809;  2042; F3-Meal;\n',
 '     1;  11.09.2019; 03:47; 04:49;  0x84;   80.91;   9.48;   3.39;   3.11; 1568162821; 1568166583;      63;    71;  2096;  2166; F3-Meal;\n',
 '     2;  11.09.2019; 04:49; 05:40;  0x84;   66.29;   7.62;   2.83;   2.59; 1568166583; 1568169618;      51;    51;  2166;  2216; F3-Meal;\n',
 '     3;  11.09.2019; 09:00; 11:19;  0x84;  383.90;  29.42;  21.02;  19.27; 1568181633; 1568189948;     139;   135;  2414;  2548; F3-Meal;\n',
 '     4;  11.09.2019; 11:41; 12:18;  0x84;   45.62;   6.12;   1.67;   1.53; 1568191283; 1568193529;      38;    46;  2565;  2610; F3-Meal;\n',
 '     5;  11.09.2019; 13:41; 16:09;  0x84;  352.79;  25.58;  19.77;  18.13; 1568198506; 1568207366;     148;   143;  2692;  2834; F3-Meal;\n',
 '     6;  11.09.2019; 16:09; 18:03;  0x84;  269.93;  19.59;  15.13;  13.86; 1568207366; 1568214223;     115;   118;  2834;  2951; F3-Meal;\n',
 '     7;  11.09.2019; 18:03; 20:36;  0x84;  328.70;  25.84;  17.79;  16.31; 1568214223; 1568223387;     153;   152;  2951;  3102; F3-Meal;\n',
 '     8;  11.09.2019; 21:19; 00:07;  0x84;  399.11;  29.30;  22.26;  20.40; 1568225997; 1568236071;     168;   167;  3145;  3311; F3-Meal;\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- All saved meals -------------------------------\n',
 "     there's no per-meal data\n",
 '-----------------------------------------------------\n',
 '\n',
 '--- Total per-file (0: by summaries, 1: by meals) -\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '11.09.2019 00:00:27; 11.09.2019 23:59:46;       0;       0; 1568246386;  2270.18;  181.33;  121.96;  111.80;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '11.09.2019 03:47:01; 12.09.2019 00:07:51;       1;       0; 1568246871;  2270.18;  181.33;  121.96;  111.80;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n',
 '\n',
 '--- Summary change history --------------------------\n',
 'Tracking Start;      Last saved;             Idx.; Rec. ID;     Tstamp;     E-IN;  CBH_in;  FAT_in;  PRO_in;    E-OUT; CBH_out; FAT_out;   Steps; Distance; E-LOSS for phy\n',
 '11.09.2019 00:00:27; 11.09.2019 23:59:46;       0;       0; 1568246386;  2270.18;  181.33;  121.96;  111.80;     0.00;    0.00;    0.00;       0;        0;           0.00\n',
 '-----------------------------------------------------\n']

In [36]:
all_data = []
scanning = False
for i in data:
    if i.startswith('-----------------------'):
        scanning = False
        continue
        
    if scanning:
        if 'Meal#' in i:
            columns_name = i
            continue
        all_data.append([i.strip() for i in i.split(';')])
        
    if 'Non-deleted saved meals' in i:
        scanning = True
        continue
all_data

[['0',
  '09.09.2019',
  '16:22',
  '17:58',
  '0x84',
  '190.19',
  '16.27',
  '9.88',
  '9.06',
  '1568035377',
  '1568041082',
  '96',
  '95',
  '4',
  '98',
  'F3-Meal',
  ''],
 ['1',
  '09.09.2019',
  '18:17',
  '20:10',
  '0x84',
  '256.30',
  '19.55',
  '14.06',
  '12.89',
  '1568042235',
  '1568049032',
  '114',
  '122',
  '108',
  '229',
  'F3-Meal',
  ''],
 ['2',
  '09.09.2019',
  '20:53',
  '21:39',
  '0x84',
  '67.63',
  '7.87',
  '2.85',
  '2.62',
  '1568051580',
  '1568054372',
  '47',
  '47',
  '271',
  '317',
  'F3-Meal',
  ''],
 ['3',
  '09.09.2019',
  '23:00',
  '00:22',
  '0x84',
  '179.50',
  '15.13',
  '9.39',
  '8.61',
  '1568059227',
  '1568064143',
  '82',
  '82',
  '397',
  '478',
  'F3-Meal',
  ''],
 ['0',
  '09.09.2019',
  '23:00',
  '00:22',
  '0x84',
  '179.50',
  '15.13',
  '9.39',
  '8.61',
  '1568059227',
  '1568064143',
  '82',
  '82',
  '397',
  '478',
  'F3-Meal',
  ''],
 ['1',
  '10.09.2019',
  '01:32',
  '02:11',
  '0x84',
  '47.41',
  '5.77',
  '1.92',
  '1.76',
  '1568068330',
  '1568070697',
  '40',
  '43',
  '544',
  '586',
  'F3-Meal',
  ''],
 ['2',
  '10.09.2019',
  '03:50',
  '05:31',
  '0x84',
  '175.42',
  '15.90',
  '8.83',
  '8.09',
  '1568076644',
  '1568082713',
  '102',
  '107',
  '678',
  '784',
  'F3-Meal',
  ''],
 ['3',
  '10.09.2019',
  '09:17',
  '10:59',
  '0x84',
  '300.08',
  '21.59',
  '16.87',
  '15.47',
  '1568096246',
  '1568102375',
  '103',
  '98',
  '1007',
  '1104',
  'F3-Meal',
  ''],
 ['4',
  '10.09.2019',
  '11:14',
  '12:07',
  '0x84',
  '76.57',
  '8.63',
  '3.32',
  '3.04',
  '1568103286',
  '1568106442',
  '53',
  '53',
  '1123',
  '1175',
  'F3-Meal',
  ''],
 ['5',
  '10.09.2019',
  '12:07',
  '12:47',
  '0x84',
  '45.03',
  '5.87',
  '1.70',
  '1.56',
  '1568106442',
  '1568108870',
  '41',
  '41',
  '1175',
  '1215',
  'F3-Meal',
  ''],
 ['6',
  '10.09.2019',
  '13:19',
  '16:05',
  '0x84',
  '371.60',
  '26.78',
  '20.88',
  '19.14',
  '1568110750',
  '1568120704',
  '166',
  '162',
  '1246',
  '1407',
  'F3-Meal',
  ''],
 ['7',
  '10.09.2019',
  '16:37',
  '18:17',
  '0x84',
  '255.73',
  '18.62',
  '14.31',
  '13.12',
  '1568122645',
  '1568128654',
  '101',
  '100',
  '1442',
  '1541',
  'F3-Meal',
  ''],
 ['8',
  '10.09.2019',
  '19:36',
  '21:34',
  '0x84',
  '303.56',
  '22.04',
  '17.01',
  '15.59',
  '1568133387',
  '1568140488',
  '119',
  '118',
  '1619',
  '1736',
  'F3-Meal',
  ''],
 ['9',
  '10.09.2019',
  '21:34',
  '23:14',
  '0x84',
  '186.06',
  '15.87',
  '9.68',
  '8.87',
  '1568140488',
  '1568146496',
  '101',
  '74',
  '1736',
  '1809',
  'F3-Meal',
  ''],
 ['10',
  '10.09.2019',
  '23:14',
  '02:44',
  '0x84',
  '460.76',
  '37.92',
  '24.40',
  '22.37',
  '1568146496',
  '1568159058',
  '210',
  '234',
  '1809',
  '2042',
  'F3-Meal',
  ''],
 ['0',
  '10.09.2019',
  '23:14',
  '02:44',
  '0x84',
  '460.76',
  '37.92',
  '24.40',
  '22.37',
  '1568146496',
  '1568159058',
  '210',
  '234',
  '1809',
  '2042',
  'F3-Meal',
  ''],
 ['1',
  '11.09.2019',
  '03:47',
  '04:49',
  '0x84',
  '80.91',
  '9.48',
  '3.39',
  '3.11',
  '1568162821',
  '1568166583',
  '63',
  '71',
  '2096',
  '2166',
  'F3-Meal',
  ''],
 ['2',
  '11.09.2019',
  '04:49',
  '05:40',
  '0x84',
  '66.29',
  '7.62',
  '2.83',
  '2.59',
  '1568166583',
  '1568169618',
  '51',
  '51',
  '2166',
  '2216',
  'F3-Meal',
  ''],
 ['3',
  '11.09.2019',
  '09:00',
  '11:19',
  '0x84',
  '383.90',
  '29.42',
  '21.02',
  '19.27',
  '1568181633',
  '1568189948',
  '139',
  '135',
  '2414',
  '2548',
  'F3-Meal',
  ''],
 ['4',
  '11.09.2019',
  '11:41',
  '12:18',
  '0x84',
  '45.62',
  '6.12',
  '1.67',
  '1.53',
  '1568191283',
  '1568193529',
  '38',
  '46',
  '2565',
  '2610',
  'F3-Meal',
  ''],
 ['5',
  '11.09.2019',
  '13:41',
  '16:09',
  '0x84',
  '352.79',
  '25.58',
  '19.77',
  '18.13',
  '1568198506',
  '1568207366',
  '148',
  '143',
  '2692',
  '2834',
  'F3-Meal',
  ''],
 ['6',
  '11.09.2019',
  '16:09',
  '18:03',
  '0x84',
  '269.93',
  '19.59',
  '15.13',
  '13.86',
  '1568207366',
  '1568214223',
  '115',
  '118',
  '2834',
  '2951',
  'F3-Meal',
  ''],
 ['7',
  '11.09.2019',
  '18:03',
  '20:36',
  '0x84',
  '328.70',
  '25.84',
  '17.79',
  '16.31',
  '1568214223',
  '1568223387',
  '153',
  '152',
  '2951',
  '3102',
  'F3-Meal',
  ''],
 ['8',
  '11.09.2019',
  '21:19',
  '00:07',
  '0x84',
  '399.11',
  '29.30',
  '22.26',
  '20.40',
  '1568225997',
  '1568236071',
  '168',
  '167',
  '3145',
  '3311',
  'F3-Meal',
  '']]

In [34]:
columns_name_final = [col.strip() for col in columns_name.split(';')]
columns_name_final

['Meal#',
 'Date',
 'Start',
 'End',
 'Flags',
 'E-IN',
 'Cbh',
 'Fat',
 'Pro',
 'S. tstamp',
 'End tstamp',
 'Minutes',
 'Recs',
 'First',
 'Last',
 'Type',
 'Frags',
 '']

In [43]:
df = pd.DataFrame(all_data, columns = columns_name_final[0:17])
df.head()

,Meal#,Date,Start,End,Flags,E-IN,Cbh,Fat,Pro,S. tstamp,End tstamp,Minutes,Recs,First,Last,Type,Frags
0,0,09.09.2019,16:22,17:58,0x84,190.19,16.27,9.88,9.06,1568035377,1568041082,96,95,4,98,F3-Meal,
1,1,09.09.2019,18:17,20:10,0x84,256.30,19.55,14.06,12.89,1568042235,1568049032,114,122,108,229,F3-Meal,
2,2,09.09.2019,20:53,21:39,0x84,67.63,7.87,2.85,2.62,1568051580,1568054372,47,47,271,317,F3-Meal,
3,3,09.09.2019,23:00,00:22,0x84,179.50,15.13,9.39,8.61,1568059227,1568064143,82,82,397,478,F3-Meal,
4,0,09.09.2019,23:00,00:22,0x84,179.50,15.13,9.39,8.61,1568059227,1568064143,82,82,397,478,F3-Meal,

In [57]:
df['Date'] = pd.to_datetime(df.Date, dayfirst = True)

In [58]:
df.dtypes

Meal#                 object
Date          datetime64[ns]
Start                 object
End                   object
Flags                 object
E-IN                  object
Cbh                   object
Fat                   object
Pro                  float64
S. tstamp             object
End tstamp            object
Minutes                int32
Recs                  object
First                 object
Last                  object
Type                  object
Frags                 object
dtype: object

In [59]:
df = df.astype({'Minutes':'int', 'Pro':'float'})
user_df = df[['Date', 'Minutes', 'Pro']]
user_df.head()

        Date  Minutes    Pro
0 2019-09-09       96   9.06
1 2019-09-09      114  12.89
2 2019-09-09       47   2.62
3 2019-09-09       82   8.61
4 2019-09-09       82   8.61

In [60]:
user_df.groupby('Date', as_index = False) \
    .agg({'Minutes':'sum'})

        Date  Minutes
0 2019-09-09      421
1 2019-10-09     1246
2 2019-11-09      875